# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('institutions', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('event_type', models.CharField(choices=[('fair', 'Education fair'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('visit', 'University visit')], default='fair', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('online_link', models.URLField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('countries', models.ManyToManyField(blank=True, related_name='events', to='destinations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('universities', models.ManyToManyField(blank=True, related_name='events', to='institutions.university')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('study_level', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlisted'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12)),
                ('attended', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='destinations.country')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
