# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('study_level', models.CharField(choices=[('foundation', 'Foundation'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD')], db_index=True, max_length=20)),
                ('discipline', models.CharField(choices=[('business', 'Business & Management'), ('engineering', 'Engineering & Technology'), ('it', 'Computer Science & IT'), ('health', 'Health & Medicine'), ('science', 'Natural Sciences'), ('arts', 'Arts & Humanities'), ('law', 'Law'), ('social', 'Social Sciences'), ('education', 'Education'), ('hospitality', 'Hospitality & Tourism'), ('agriculture', 'Agriculture')], db_index=True, max_length=30)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overview', models.TextField(blank=True)),
                ('entry_requirements', models.TextField(blank=True)),
                ('english_requirements', models.TextField(blank=True)),
                ('career_outcomes', models.TextField(blank=True)),
                ('course_url', models.URLField(blank=True)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('intakes', models.ManyToManyField(blank=True, related_name='courses', to='destinations.intake')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universities/cover/')),
                ('university_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('world_ranking', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('national_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('accreditations', models.CharField(blank=True, max_length=300)),
                ('facilities', models.TextField(blank=True, help_text='One item per line')),
                ('tuition_min', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_max', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('international_students', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_partner', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='destinations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['world_ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='institutions.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='institutions.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='institutions.university'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country', 'is_active'], name='institution_country_3549c9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['study_level', 'discipline'], name='institution_study_l_472a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'university'], name='institution_is_acti_a14b52_idx'),
        ),
    ]
