# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Dream Spot Global', max_length=120)),
                ('tagline', models.CharField(default='Education • Career • Immigration', max_length=160)),
                ('business_type', models.CharField(default='Study Abroad Education Consultancy', max_length=120)),
                ('about_short', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('address', models.CharField(default='House 21, Road 01, Sector 9, Uttara, Dhaka, Bangladesh', max_length=255)),
                ('phone_primary', models.CharField(default='+880 1410-157209', max_length=32)),
                ('phone_secondary', models.CharField(blank=True, default='+880 1612649451', max_length=32)),
                ('email', models.EmailField(default='dreamspotglobal@gmail.com', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='8801410157209', max_length=32)),
                ('office_hours', models.CharField(blank=True, default='Saturday – Thursday, 10:00 AM – 7:00 PM', max_length=160)),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps iframe embed code')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/dreamspotglobalpage')),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('stat_students', models.CharField(default='1,200+', max_length=20)),
                ('stat_universities', models.CharField(default='450+', max_length=20)),
                ('stat_visa_success', models.CharField(default='97%', max_length=20)),
                ('stat_countries', models.CharField(default='8', max_length=20)),
                ('ga4_id', models.CharField(blank=True, max_length=40)),
                ('gtm_id', models.CharField(blank=True, max_length=40)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=40)),
                ('search_console_token', models.CharField(blank=True, max_length=120)),
                ('lead_assignment_mode', models.CharField(choices=[('round_robin', 'Round robin'), ('by_country', 'By destination country'), ('manual', 'Manual only')], default='round_robin', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, max_length=255)),
                ('default_meta_title', models.CharField(blank=True, max_length=180)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=180)),
                ('subheading', models.CharField(blank=True, max_length=320)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_text', models.CharField(blank=True, default='Book Free Counselling', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='/book-counselling/', max_length=255)),
                ('cta2_text', models.CharField(blank=True, default='Explore Destinations', max_length=60)),
                ('cta2_url', models.CharField(blank=True, default='/study-abroad/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('stats', 'Trust bar'), ('destinations', 'Study destinations'), ('services', 'Our services'), ('why_us', 'Why Dream Spot Global'), ('journey', 'Your study abroad journey'), ('universities', 'Featured universities'), ('scholarships', 'Scholarship highlights'), ('events', 'Upcoming events'), ('testimonials', 'Success stories'), ('blog', 'Latest from the blog'), ('faq', 'FAQ'), ('cta', 'Free assessment CTA')], max_length=32, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('heading', models.CharField(blank=True, max_length=160)),
                ('subheading', models.CharField(blank=True, max_length=320)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='compass', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(db_index=True, max_length=300, unique=True)),
                ('new_path', models.CharField(max_length=300)),
                ('is_permanent', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('designation', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='award', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('view', 'Sensitive view')], max_length=12)),
                ('model_name', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx')],
            },
        ),
    ]
