# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('study_level', models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD')], max_length=20)),
                ('intended_intake', models.CharField(blank=True, choices=[('jan', 'January'), ('may', 'May / Summer'), ('sep', 'September / Fall')], max_length=10)),
                ('last_qualification', models.CharField(blank=True, max_length=160)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('english_test', models.CharField(choices=[('none', 'Not taken'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('moi', 'MOI')], default='none', max_length=12)),
                ('english_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('homepage_cta', 'Homepage CTA'), ('contact', 'Contact page'), ('service_page', 'Service page'), ('destination_page', 'Destination page'), ('course_page', 'Course page'), ('scholarship_page', 'Scholarship page'), ('assessment', 'Free assessment'), ('appointment', 'Counselling booking'), ('event', 'Event registration'), ('walk_in', 'Walk-in'), ('facebook', 'Facebook'), ('referral', 'Referral'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('scheduled', 'Counselling scheduled'), ('converted', 'Converted'), ('not_interested', 'Not interested'), ('invalid', 'Invalid'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('next_follow_up', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consent_given', models.BooleanField(default=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_result', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.staffprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinations', models.ManyToManyField(blank=True, related_name='leads', to='destinations.country')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status change'), ('assigned', 'Assigned'), ('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('enquiry', 'Repeat enquiry'), ('converted', 'Converted'), ('note', 'Note')], default='note', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leads/notes/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirm_token', models.CharField(blank=True, max_length=64)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='leads_lead_status_a53442_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at', 'source'], name='leads_lead_created_3d9ba8_idx'),
        ),
    ]
