# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=3)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries/flags/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='countries/hero/')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='countries/card/')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('overview', models.TextField(blank=True)),
                ('why_study', models.TextField(blank=True)),
                ('education_system', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('english_requirements', models.TextField(blank=True)),
                ('visa_process', models.TextField(blank=True)),
                ('post_study_work', models.TextField(blank=True)),
                ('part_time_work', models.TextField(blank=True)),
                ('tuition_min', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_max', models.PositiveIntegerField(blank=True, null=True)),
                ('living_cost_min', models.PositiveIntegerField(blank=True, null=True)),
                ('living_cost_max', models.PositiveIntegerField(blank=True, null=True)),
                ('visa_duration', models.CharField(blank=True, max_length=80)),
                ('work_hours_allowed', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostOfLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_min', models.PositiveIntegerField(default=0)),
                ('accommodation_max', models.PositiveIntegerField(default=0)),
                ('food_min', models.PositiveIntegerField(default=0)),
                ('food_max', models.PositiveIntegerField(default=0)),
                ('transport_min', models.PositiveIntegerField(default=0)),
                ('transport_max', models.PositiveIntegerField(default=0)),
                ('utilities_min', models.PositiveIntegerField(default=0)),
                ('utilities_max', models.PositiveIntegerField(default=0)),
                ('misc_min', models.PositiveIntegerField(default=0)),
                ('misc_max', models.PositiveIntegerField(default=0)),
                ('bdt_rate', models.DecimalField(decimal_places=2, default=0, help_text='1 unit of local currency in BDT', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='destinations.country')),
            ],
            options={
                'verbose_name_plural': 'Cost of living',
            },
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_items', to='destinations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('months', models.CharField(blank=True, max_length=80)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='destinations.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application_deadline', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
