# Generated by Django 5.1.15 on 2026-09-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('intake', models.CharField(blank=True, max_length=40)),
                ('study_level', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(choices=[('enquiry', 'Enquiry'), ('counselling', 'Counselling'), ('documents', 'Documents'), ('university_application', 'University application'), ('offer_received', 'Offer received'), ('offer_accepted', 'Offer accepted'), ('deposit_paid', 'Tuition / deposit paid'), ('cas_issued', 'CAS / I-20 / COE issued'), ('visa_applied', 'Visa application'), ('visa_granted', 'Visa granted'), ('pre_departure', 'Pre-departure'), ('departed', 'Departed')], db_index=True, default='enquiry', max_length=30)),
                ('sub_status', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('offer_type', models.CharField(blank=True, choices=[('conditional', 'Conditional'), ('unconditional', 'Unconditional')], max_length=20)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('offer_received_on', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('visa_status', models.CharField(choices=[('not_applied', 'Not applied'), ('applied', 'Applied'), ('biometrics', 'Biometrics done'), ('interview', 'Interview scheduled'), ('granted', 'Granted'), ('refused', 'Refused')], default='not_applied', max_length=20)),
                ('visa_applied_on', models.DateField(blank=True, null=True)),
                ('biometrics_on', models.DateField(blank=True, null=True)),
                ('interview_on', models.DateField(blank=True, null=True)),
                ('visa_decision_on', models.DateField(blank=True, null=True)),
                ('visa_refusal_reason', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.staffprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='institutions.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='institutions.university')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=30)),
                ('to_stage', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'Application stage history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Academic transcript'), ('certificate', 'Academic certificate'), ('english_test', 'IELTS / PTE scorecard'), ('sop', 'Statement of Purpose'), ('lor', 'Letter of Recommendation'), ('cv', 'CV / Résumé'), ('bank_statement', 'Bank statement'), ('photograph', 'Photograph'), ('experience', 'Experience letter'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reupload', 'Re-upload requested')], db_index=True, default='pending', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=400)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stage', 'assigned_officer'], name='application_stage_df0470_idx'),
        ),
    ]
